package com.myapp.recipe.application;

import com.my.common.api.UserId;
import com.myapp.recipe.EmbeddedPostgresResource;
import com.myapp.recipe.domain.model.*;
import io.quarkus.test.common.QuarkusTestResource;
import io.quarkus.test.junit.QuarkusTest;
import jakarta.inject.Inject;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestInstance;

import java.time.Duration;
import java.util.HashSet;
import java.util.List;
import java.util.Optional;
import java.util.Set;

import static org.junit.jupiter.api.Assertions.*;

@QuarkusTest
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
@QuarkusTestResource(EmbeddedPostgresResource.class)
public class RecipeServiceTest {

    private static final UserId USER_ID = new UserId("1");

    @Inject
    RecipeService recipeService;

    @Test
    public void testGetRecipeById() {
        Optional<Recipe> recipe = recipeService.getById(new RecipeId(1));
        assertTrue(recipe.isPresent());

        assertEquals("Chocolate Cake", recipe.get().name());
        assertEquals(8, recipe.get().portions());
        assertEquals(Duration.ofMinutes(60), recipe.get().duration());

        assertEquals(8, recipe.get().recipeIngredients().size());
        assertEquals(5, recipe.get().cookingInstructions().size());
    }

    @Test
    public void testGetAllRecipes() {
        List<Recipe> recipes = recipeService.getAllByUser(USER_ID);
        assertEquals(4, recipes.size());

        Recipe recipe = recipes.getFirst();
        assertEquals("Chocolate Cake", recipe.name());
        assertEquals(8, recipe.portions());
        assertEquals(Duration.ofMinutes(60), recipe.duration());
    }

    @Test
    public void testCreateRecipe() {
        Recipe newRecipe = new Recipe(
                new RecipeId(0),
                "New Recipe",
                Set.of(
                        new RecipeIngredient(new Ingredient("Flour", ProductCategory.BAKERY), 200, Unit.GRAM),
                        new RecipeIngredient(new Ingredient("Milk", ProductCategory.DAIRY), 500, Unit.MILLILITER)
                ),
                List.of(
                        new CookingInstruction("Mix the flour and milk.", Set.of(
                                new RecipeIngredient(new Ingredient("Flour", ProductCategory.BAKERY), 200, Unit.GRAM),
                                new RecipeIngredient(new Ingredient("Milk", ProductCategory.DAIRY), 500, Unit.MILLILITER)
                        )),
                        new CookingInstruction("Bake at 180 degrees for 20 minutes.", Set.of())
                ),
                2,
                Duration.ofMinutes(20), new HashSet<>(List.of(new Tag("leicht"))),
                USER_ID
        );

        Recipe savedRecipe = recipeService.createRecipe(newRecipe);

        assertNotNull(savedRecipe);
        assertEquals("New Recipe", savedRecipe.name());

        Optional<Recipe> fetchedRecipe = recipeService.getById(savedRecipe.id());
        assertTrue(fetchedRecipe.isPresent());

        Recipe r = fetchedRecipe.get();
        assertEquals("New Recipe", r.name());
        assertEquals(2, r.portions());
        assertEquals(Duration.ofMinutes(20), r.duration());

        assertEquals(2, r.recipeIngredients().size());
        assertEquals(2, r.cookingInstructions().size());
    }

    @Test
    public void testRemoveRecipeById() {
        Recipe newRecipe = new Recipe(
                new RecipeId(0), // ID generated by DB
                "Temp Recipe",
                Set.of(
                        new RecipeIngredient(new Ingredient("Flour", ProductCategory.BAKERY), 200, Unit.GRAM),
                        new RecipeIngredient(new Ingredient("Milk", ProductCategory.DAIRY), 500, Unit.MILLILITER)
                ),
                List.of(
                        new CookingInstruction("Mix the ingredients.", Set.of(
                                new RecipeIngredient(new Ingredient("Flour", ProductCategory.BAKERY), 200, Unit.GRAM),
                                new RecipeIngredient(new Ingredient("Milk", ProductCategory.DAIRY), 500, Unit.MILLILITER)
                        )),
                        new CookingInstruction("Bake at 180 degrees.", Set.of())
                ),
                2,
                Duration.ofMinutes(20),
                new HashSet<>(List.of(new Tag("leicht"))),
                USER_ID
        );

        Recipe saved = recipeService.createRecipe(newRecipe);
        RecipeId idToRemove = saved.id();

        assertTrue(recipeService.getById(idToRemove).isPresent());

        recipeService.deleteById(saved.id());
        assertFalse(recipeService.getById(idToRemove).isPresent());
    }

    @Test
    public void testGetIngredientsByMeals() {

    }
}
